POST http://localhost:5214/api/v1/products
Content-Type: application/json

{
  "Id": "71dac2c3-9c1b-4f1a-9934-dab5a99f4090",
  "Name": "Example Product",
  "BrandId": "2b077288-ae13-4848-adf1-d3f6d527aecd",
  "BrandName": "Example Brand",
  "BrandProducts": ["Product 1", "Product 2"],
  "ColorId": "85d7a720-bfb4-40df-b91d-86173b196ff0",
  "ColorType": 1,
  "Number": 100,
  "ColorName": "Red",
  "Visible": true,
  "ProductionItemId": "d01fe9b4-15d9-493e-a8d1-eb4d01ecb369",
  "ProductionItemCreatedDate": 1672522560000,
  "ProductMetadataProductNumber": "MD123",
  "ProductMetadataKey": "Key123",
  "ProductMetadaProductNumber": 123,
  "ProductMetadaTenantId": 456,
  "ProductMetadaProductionItems": ["Item 1", "Item 2"],
  "StoreIds": ["Store1", "Store2"],
  "StoreId": "7c3ce2f4-532d-4fc1-ac3c-e12504c35016",
  "StockPointId": 789,
  "StockVariantId": "497788aa-f9ba-483b-8b69-1b83c98d5300",
  "StockQuantity": 50,
  "StockPreOrderQuantity": 10,
  "StockConcessionQuantity": 5,
  "StockUnaccessibleQuantity": 2,
  "StockProductItems": ["Stock Item 1", "Stock Item 2"]
}
